// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izigxcwrrgpxanpruiqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6aWd4Y3dycmdweGFucHJ1aXFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTg2NDIsImV4cCI6MjA3MTUzNDY0Mn0.yxdNr5pTJ2s_4ZtaFDypeB9Wf011W0XlNopIb18tPOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});